yelp_clone/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
get 'restaurants' => 'restaurants#index'

root to: "restaurants#index"


resources :restaurants do
  resources :reviews
end

end

yelp_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, length: { minimum: 3 }, uniqueness: true
  has_many :reviews, -> { extending WithUserAssociationExtension }, dependent: :destroy
  belongs_to :user

end

yelp_clone/app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }

  belongs_to :user
  belongs_to :restaurant

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end
end

yelp_clone/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

end

yelp_clone/app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

yelp_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
   @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    user = User.find(current_user.id)
    @restaurant = user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end


  private

  def restaurant_params
  params.require(:restaurant).permit(:name, :description)
  end

end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)

    if @review.save
        redirect_to '/restaurants'
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: "You have already reviewed this restaurant"
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

yelp_clone/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

yelp_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

yelp_clone/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper
end

yelp_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- <%= notice %> -->
    <%= yield %>
  </body>
</html>

yelp_clone/app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |x| %>
  <%= x.label :name %>
  <%= x.text_field :name %>
  <%= x.label :description %>
  <%= x.text_area :description %>
  <%= x.submit %>
<% end %>

yelp_clone/app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

yelp_clone/app/views/restaurants/index.html.erb
<% if @restaurant.any? %>
  <% @restaurant.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <h2><%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %></h2>
    <h2><%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <h2><%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %></h2>
    <% restaurant.reviews.each do |review| %>
      <p><%= review.thoughts %></p>
      <p><%= review.rating %></p>
    <% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="/restaurants/new">Add a restaurant</a>

yelp_clone/app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    %p= restaurant.description
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), :method => :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    - if restaurant.reviews.any?
      - restaurant.reviews.each do |review|
        %p= review.thoughts
        %p= review.rating
- else
  %h1 No restaurants yet

= link_to "Add a restaurant", new_restaurant_path

yelp_clone/app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>

<section id="errors" >
  <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
</section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

yelp_clone/app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2= pluralize @restaurant.errors.count, "error"
    prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message
        
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

yelp_clone/app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

yelp_clone/app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

yelp_clone/app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>

yelp_clone/app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'